-- ZolNutrition v3: faster logging + saved meals + training/rest targets
-- Run once after the existing base schema and V2 onboarding migration.

alter table public.nutrition_goals
  add column if not exists training_day_calories numeric,
  add column if not exists training_day_protein numeric,
  add column if not exists training_day_carbs numeric,
  add column if not exists training_day_fat numeric,
  add column if not exists rest_day_calories numeric,
  add column if not exists rest_day_protein numeric,
  add column if not exists rest_day_carbs numeric,
  add column if not exists rest_day_fat numeric,
  add column if not exists training_days integer[] not null default array[1,3,5]::integer[];

update public.nutrition_goals set
  training_day_calories = coalesce(training_day_calories,daily_calories),
  training_day_protein = coalesce(training_day_protein,daily_protein),
  training_day_carbs = coalesce(training_day_carbs,daily_carbs),
  training_day_fat = coalesce(training_day_fat,daily_fat),
  rest_day_calories = coalesce(rest_day_calories,daily_calories),
  rest_day_protein = coalesce(rest_day_protein,daily_protein),
  rest_day_carbs = coalesce(rest_day_carbs,daily_carbs),
  rest_day_fat = coalesce(rest_day_fat,daily_fat);

alter table public.nutrition_goals
  drop constraint if exists nutrition_goals_training_days_check,
  add constraint nutrition_goals_training_days_check check (
    training_days <@ array[0,1,2,3,4,5,6]::integer[]
  );

create table if not exists public.saved_meals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 1 and 60),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.saved_meal_items (
  id bigint generated by default as identity primary key,
  saved_meal_id bigint not null references public.saved_meals(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  food_id bigint references public.foods(id) on delete set null,
  food_name text not null,
  quantity_g numeric not null check (quantity_g > 0),
  calories numeric not null default 0,
  protein numeric not null default 0,
  carbs numeric not null default 0,
  fat numeric not null default 0,
  sort_order integer not null default 0
);

create index if not exists saved_meals_user_idx on public.saved_meals(user_id, created_at desc);
create index if not exists saved_meal_items_meal_idx on public.saved_meal_items(saved_meal_id, sort_order);

alter table public.saved_meals enable row level security;
alter table public.saved_meal_items enable row level security;

drop policy if exists "saved_meals_select_own" on public.saved_meals;
drop policy if exists "saved_meals_insert_own" on public.saved_meals;
drop policy if exists "saved_meals_update_own" on public.saved_meals;
drop policy if exists "saved_meals_delete_own" on public.saved_meals;
create policy "saved_meals_select_own" on public.saved_meals for select to authenticated using ((select auth.uid())=user_id);
create policy "saved_meals_insert_own" on public.saved_meals for insert to authenticated with check ((select auth.uid())=user_id);
create policy "saved_meals_update_own" on public.saved_meals for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
create policy "saved_meals_delete_own" on public.saved_meals for delete to authenticated using ((select auth.uid())=user_id);

drop policy if exists "saved_meal_items_select_own" on public.saved_meal_items;
drop policy if exists "saved_meal_items_insert_own" on public.saved_meal_items;
drop policy if exists "saved_meal_items_update_own" on public.saved_meal_items;
drop policy if exists "saved_meal_items_delete_own" on public.saved_meal_items;
create policy "saved_meal_items_select_own" on public.saved_meal_items for select to authenticated using ((select auth.uid())=user_id);
create policy "saved_meal_items_insert_own" on public.saved_meal_items for insert to authenticated with check ((select auth.uid())=user_id);
create policy "saved_meal_items_update_own" on public.saved_meal_items for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
create policy "saved_meal_items_delete_own" on public.saved_meal_items for delete to authenticated using ((select auth.uid())=user_id);

grant select,insert,update,delete on public.saved_meals to authenticated;
grant select,insert,update,delete on public.saved_meal_items to authenticated;
grant usage,select on sequence public.saved_meals_id_seq to authenticated;
grant usage,select on sequence public.saved_meal_items_id_seq to authenticated;
